<a href="https://colab.research.google.com/github/PiyushBans/MCA_Big_data/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
'''1. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) ) '''
arr =np.array([1,2,3,6,4,5])
reverse_array = arr[::-1]
print(reverse_array)

[5 4 6 3 2 1]


In [3]:
'''2. Compare the following numpy arrays: arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]]) '''

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

are_equal = np.array_equal(arr1, arr2)
print("Are the arrays equal?", are_equal)

Are the arrays equal? True


In [4]:
'''3. Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) '''

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
counts = np.bincount(x)
most_frequent_value = np.argmax(counts)
most_frequent_indices = np.where(x == most_frequent_value)[0]

print("Most frequent value in x:", most_frequent_value)
print("Indices of the most frequent value in x:", most_frequent_indices)


Most frequent value in x: 1
Indices of the most frequent value in x: [0 5 7 8 9]


In [6]:
'''4. For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'),
find i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise '''

gfg = np.matrix('4, 1, 9; 12, 3, 1; 4, 5, 6')

# i. Sum of all elements
total_sum = np.sum(gfg)

# ii. Sum of all elements row-wise
row_sum = np.sum(gfg, axis=1)

# iii. Sum of all elements column-wise
col_sum = np.sum(gfg, axis=0)

print("Sum of all elements:", total_sum)
print("Sum of all elements row-wise:", row_sum)
print("Sum of all elements column-wise:", col_sum)
print(gfg)

Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
